"use client";

import { useActionState } from "react";
import { assignAccountAction, changeStatusAction, createInteractionAction, createTaskAction, updateBrandSettingsAction } from "@/app/(protected)/dashboard/commercial/actions";
import { ActionFeedback } from "@/components/reference/action-feedback";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type UserOption = { id: string; name: string };
type ContactOption = { id: string; name: string };
const taskTypes = ["call", "email", "visit", "appointment", "send_offer", "follow_up", "qualify", "update_contact", "check_stock", "request_order", "internal_review", "other"];
const statuses = ["targeted", "qualified", "contacted", "appointment_scheduled", "offer_sent", "pending_order", "implanted", "active", "to_develop", "dormant", "lost"];

export function StatusChangeForm({ brandPharmacyId, currentStatus, compact = false }: { brandPharmacyId: string; currentStatus: string; compact?: boolean }) {
  const [state, action, pending] = useActionState(changeStatusAction, {});
  return <form action={action} className={compact ? "space-y-2" : "grid gap-3 sm:grid-cols-2"}><input type="hidden" name="brandPharmacyId" value={brandPharmacyId} /><ActionFeedback {...state} /><div className="space-y-2"><Label>Nouveau statut</Label><Select name="status" defaultValue={currentStatus}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{statuses.map((status) => <SelectItem key={status} value={status}>{status.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Motif si étape sautée ou réactivation</Label><Input name="reason" placeholder="Motif de la transition" /></div><Button disabled={pending} className={compact ? "w-full" : "sm:col-span-2"}>{pending ? "Mise à jour…" : "Confirmer la transition"}</Button></form>;
}

export function TaskForm({ brandPharmacyId, users, currentUserId }: { brandPharmacyId: string; users: UserOption[]; currentUserId: string }) {
  const [state, action, pending] = useActionState(createTaskAction, {});
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="brandPharmacyId" value={brandPharmacyId} /><div className="sm:col-span-2"><ActionFeedback {...state} /></div><div className="space-y-2"><Label>Type</Label><Select name="taskType" defaultValue="follow_up"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{taskTypes.map((type) => <SelectItem key={type} value={type}>{type.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Priorité</Label><Select name="priority" defaultValue="normal"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["low", "normal", "high", "urgent"].map((priority) => <SelectItem key={priority} value={priority}>{priority}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Titre</Label><Input name="title" required /></div><div className="space-y-2"><Label>Échéance</Label><Input name="dueAt" type="datetime-local" /></div><div className="space-y-2"><Label>Responsable</Label><Select name="assignedTo" defaultValue={currentUserId}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{users.map((user) => <SelectItem key={user.id} value={user.id}>{user.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Description</Label><Textarea name="description" /></div><Button disabled={pending} className="sm:col-span-2">Créer la tâche</Button></form>;
}

export function InteractionForm({ brandPharmacyId, users, contacts, currentUserId, role }: { brandPharmacyId: string; users: UserOption[]; contacts: ContactOption[]; currentUserId: string; role: string }) {
  const [state, action, pending] = useActionState(createInteractionAction, {});
  const visibilityOptions =
    role === "tr1_manager" || role === "super_admin"
      ? [["shared", "Partagée"], ["tr1_internal", "Interne TR1"], ["brand_internal", "Interne marque"]]
      : role === "brand_admin" || role === "brand_user"
        ? [["shared", "Partagée"], ["brand_internal", "Interne marque"]]
        : [["shared", "Partagée"]];
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="brandPharmacyId" value={brandPharmacyId} /><div className="sm:col-span-2"><ActionFeedback {...state} /></div><div className="space-y-2"><Label>Canal</Label><Select name="interactionType" defaultValue="call"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["call", "email", "visit", "video_call", "message", "linkedin", "event", "internal_note", "other"].map((type) => <SelectItem key={type} value={type}>{type.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Résultat</Label><Select name="outcome" defaultValue="completed"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["no_answer", "callback_requested", "information_sent", "appointment_booked", "offer_requested", "offer_sent", "interested", "not_interested", "decision_pending", "order_expected", "completed", "other"].map((value) => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Date</Label><Input name="occurredAt" type="datetime-local" required /></div><div className="space-y-2"><Label>Visibilité</Label><Select name="visibility" defaultValue="shared"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{visibilityOptions.map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Objet</Label><Input name="subject" required /></div><div className="space-y-2 sm:col-span-2"><Label>Compte rendu</Label><Textarea name="notes" /></div>{contacts.length ? <div className="space-y-2"><Label>Contact</Label><Select name="contactId"><SelectTrigger className="w-full"><SelectValue placeholder="Aucun" /></SelectTrigger><SelectContent>{contacts.map((contact) => <SelectItem key={contact.id} value={contact.id}>{contact.name}</SelectItem>)}</SelectContent></Select></div> : null}<div className="space-y-2"><Label>Prochaine action</Label><Select name="nextTaskType"><SelectTrigger className="w-full"><SelectValue placeholder="Aucune" /></SelectTrigger><SelectContent>{taskTypes.map((type) => <SelectItem key={type} value={type}>{type.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Échéance suivante</Label><Input name="nextTaskAt" type="datetime-local" /></div><div className="space-y-2"><Label>Responsable suivant</Label><Select name="nextTaskOwner" defaultValue={currentUserId}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{users.map((user) => <SelectItem key={user.id} value={user.id}>{user.name}</SelectItem>)}</SelectContent></Select></div><Button disabled={pending} className="sm:col-span-2">Enregistrer l’interaction</Button></form>;
}

export function AssignmentForm({ brandPharmacyId, users }: { brandPharmacyId: string; users: UserOption[] }) {
  const [state, action, pending] = useActionState(assignAccountAction, {});
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="brandPharmacyId" value={brandPharmacyId} /><div className="sm:col-span-2"><ActionFeedback {...state} /></div><div className="space-y-2"><Label>Utilisateur</Label><Select name="userId" required><SelectTrigger className="w-full"><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent>{users.map((user) => <SelectItem key={user.id} value={user.id}>{user.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Type</Label><Select name="assignmentType" defaultValue="commercial_agent"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="commercial_agent">Agent commercial</SelectItem><SelectItem value="tr1_manager">Responsable TR1</SelectItem><SelectItem value="brand_manager">Responsable marque</SelectItem><SelectItem value="temporary_backup">Remplacement</SelectItem></SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Motif</Label><Input name="reason" /></div><Button disabled={pending} className="sm:col-span-2">Attribuer ou réattribuer</Button></form>;
}

export function BrandSettingsForm({ settings }: { settings: Record<string, number | boolean | null> }) {
  const [state, action, pending] = useActionState(updateBrandSettingsAction, {});
  const numberFields = [["defaultDelay","default_follow_up_delay_days","Relance par défaut (jours)"],["offerDelay","offer_follow_up_delay_days","Relance offre (jours)"],["pendingDelay","pending_order_follow_up_delay_days","Attente commande (jours)"],["appointmentHours","appointment_reminder_delay_hours","Rappel rendez-vous (heures)"],["activeMaxDays","active_max_days","Actif jusqu’à (jours)"],["watchStartDays","watch_start_days","À surveiller dès (jours)"],["atRiskStartDays","at_risk_start_days","À risque dès (jours)"],["dormantStartDays","dormant_start_days","Dormant dès (jours)"],["postImplantationDays","post_implantation_follow_up_days","Suivi implantation (jours)"],["expectedReorderDays","expected_first_reorder_days","Premier réassort attendu (jours)"],["dormantFollowUpDays","dormant_reactivation_follow_up_days","Relance dormance (jours)"]];
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><ActionFeedback {...state} /></div>{numberFields.map(([name,key,label]) => <div key={name}><Label>{label}</Label><Input name={name} type="number" min="0" defaultValue={Number(settings[key])} /></div>)}{[["requireNextAction", "require_next_action", "Exiger une prochaine action"], ["agentsChangeStatus", "allow_agents_to_change_status", "Agents : changer le statut"], ["agentsCreateContacts", "allow_agents_to_create_contacts", "Agents : créer des contacts"], ["agentsEditPotential", "allow_agents_to_edit_potential", "Agents : modifier le potentiel"], ["automaticActivity", "automatic_activity_status_enabled", "Recalcul automatique de l’activité"]].map(([name, key, label]) => <label key={name} className="flex items-center gap-2 text-sm"><input type="checkbox" name={name} defaultChecked={Boolean(settings[key])} />{label}</label>)}<Button disabled={pending} className="sm:col-span-2">Enregistrer</Button></form>;
}
