import Link from "next/link";
import { redirect } from "next/navigation";
import { ProposalReviewForm } from "@/components/missions/forms";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getBrandContexts, requireActiveBrand } from "@/lib/auth";
import { isoToParisLocal } from "@/lib/agenda";
import { uiLabel } from "@/lib/ui-copy";

export default async function MissionProposalsPage(){const{supabase,brand}=await requireActiveBrand();const contexts=await getBrandContexts();const role=contexts.find((item)=>item.id===brand.id)?.role??"brand_user";if(!["brand_admin","tr1_manager","super_admin"].includes(role))redirect("/dashboard/missions");const{data,error}=await supabase.from("missions").select("id,title,mission_type,scheduled_start_at,scheduled_end_at,budget_estimated_ht,objective,briefing,assigned_user_id,users!missions_assigned_user_id_fkey(user_profiles(full_name)),pharmacies(trade_name,legal_name,city),mission_products(products(name,sku))").eq("brand_id",brand.id).eq("proposal_source","provider").eq("proposal_review_status","pending").is("archived_at",null).order("created_at",{ascending:true});if(error)throw new Error(error.message);return <div className="space-y-5"><header><p className="font-mono text-xs font-bold uppercase text-[var(--tr1-orange)]">Missions · {brand.name}</p><h1 className="text-3xl font-black text-[var(--tr1-navy)]">Propositions à valider</h1><p className="text-sm text-muted-foreground">La planification n’est officielle qu’après succès de la validation.</p></header>{(data??[]).map((mission)=>{const pharmacy=Array.isArray(mission.pharmacies)?mission.pharmacies[0]:mission.pharmacies;const user=Array.isArray(mission.users)?mission.users[0]:mission.users;const profile=Array.isArray(user?.user_profiles)?user.user_profiles[0]:user?.user_profiles;return <Card key={mission.id}><CardHeader><div className="flex flex-wrap justify-between gap-2"><div><CardTitle><Link href={`/dashboard/missions/${mission.id}`}>{mission.title}</Link></CardTitle><p className="text-sm text-muted-foreground">{pharmacy?.trade_name||pharmacy?.legal_name} · {pharmacy?.city} · {profile?.full_name||"Intervenant"}</p></div><div className="flex gap-2"><Badge>{uiLabel(mission.mission_type)}</Badge><Badge variant="secondary">En attente</Badge></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 text-sm sm:grid-cols-3"><p><strong>Créneau</strong><br/>{mission.scheduled_start_at?isoToParisLocal(mission.scheduled_start_at).replace("T"," "):"À préciser"}</p><p><strong>Budget proposé</strong><br/>{Number(mission.budget_estimated_ht??0).toLocaleString("fr-FR")} € HT</p><p><strong>Produits</strong><br/>{mission.mission_products?.map((entry)=>{const product=Array.isArray(entry.products)?entry.products[0]:entry.products;return product?.name}).filter(Boolean).join(", ")||"Aucun"}</p></div><p className="text-sm"><strong>Objectif :</strong> {mission.objective}</p><p className="whitespace-pre-wrap text-sm"><strong>Brief :</strong> {mission.briefing||"—"}</p><ProposalReviewForm mission={mission}/></CardContent></Card>})}{!data?.length?<Card><CardContent className="p-8 text-center text-sm text-muted-foreground">Aucune proposition en attente.</CardContent></Card>:null}</div>}
