import Link from "next/link";

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen overflow-x-hidden bg-[#fffdf8] text-[#0b1e32]">
    <header className="sticky top-0 z-40 border-b border-[#0b1e32]/10 bg-[#fffdf8]/90 backdrop-blur-xl"><div className="mx-auto flex h-[4.6rem] max-w-7xl items-center gap-6 px-5 lg:px-8"><Link className="flex items-center gap-3" href="/"><span className="relative grid size-10 place-items-center rounded-xl bg-[#0b1e32] font-mono text-[.65rem] font-black text-white after:absolute after:right-1.5 after:top-1.5 after:size-1.5 after:rounded-full after:bg-[#ef6a3a]">TR1</span><span><strong className="block text-sm font-black tracking-[-.02em]">TR1 Pharma</strong><small className="block font-mono text-[.52rem] font-bold uppercase tracking-[.12em] text-[#667384]">Terrain intelligence</small></span></Link><nav className="ml-auto hidden items-center gap-6 text-sm font-semibold text-[#445265] lg:flex"><Link className="hover:text-[#c84f24]" href="/#probleme">Pourquoi TR1</Link><Link className="hover:text-[#c84f24]" href="/#valeur">La valeur</Link><Link className="hover:text-[#c84f24]" href="/#produit">La plateforme</Link><Link className="hover:text-[#c84f24]" href="/#equipes">Les équipes</Link></nav><Link className="hidden rounded-xl bg-[#c84f24] px-4 py-2.5 text-xs font-black text-white xl:inline-flex" href="/#diagnostic">Découvrir TR1 sur mon réseau officinal</Link><Link className="ml-auto rounded-xl border border-[#0b1e32]/15 px-4 py-2.5 font-mono text-[.66rem] font-black uppercase tracking-[.05em] lg:ml-0" href="/connexion">Connexion</Link></div></header>
    {children}
    <footer className="border-t border-[#d8d0c2] px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-[#66717d] sm:flex-row"><p>© 2026 TR1 Pharma — Pilotage commercial et exécution terrain.</p><div className="flex gap-4"><Link href="/mentions-legales">Mentions légales</Link><Link href="/politique-de-confidentialite">Confidentialité</Link></div></div></footer>
  </div>;
}
