import { ArrowDown, ArrowRight, Building2, ChartNoAxesCombined, Route, ShieldCheck } from "lucide-react";
import { LeadForm } from "@/components/marketing/lead-form";
import { MarketingPageEvent, MarketingTrackedLink } from "@/components/marketing/marketing-events";
import { ProductProof } from "@/components/marketing/product-proof";

const pillars = [
  { icon: Building2, title: "Structurez votre réseau", text: "Centralisez pharmacies, contacts, produits, territoires et historique commercial.", items: ["Référentiel officinal", "Portefeuille partagé", "Affectations", "Données cohérentes"] },
  { icon: Route, title: "Pilotez l’exécution terrain", text: "Donnez à chaque intervenant un cadre commun, du briefing au rapport validé.", items: ["Ma journée Agent", "Missions", "Prochaines actions", "Rapports terrain"] },
  { icon: ChartNoAxesCombined, title: "Développez votre portefeuille", text: "Repérez les comptes à développer et suivez commandes, implantations et réassorts.", items: ["Priorités commerciales", "Réassorts", "Distribution", "Impact observé"] },
];

export default function LandingPage() {
  return <main><MarketingPageEvent event="landing_view" />
    <section className="border-b border-[#d8d0c2]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div className="min-w-0 self-center"><p className="font-mono text-[.68rem] font-bold uppercase tracking-[.2em] text-[#c9562d]">Le système commercial du réseau officinal</p><h1 className="mt-5 max-w-4xl break-words text-[2.65rem] font-black leading-[.94] tracking-[-.065em] text-[#0f2740] sm:text-6xl lg:text-7xl">Structurez, pilotez et développez votre réseau officinal.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#526170]">TR1 réunit vos pharmacies, vos équipes, vos commandes et vos actions terrain pour vous aider à faire grandir votre réseau sans perdre le contrôle.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><MarketingTrackedLink className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-md bg-[#0f2740] px-4 text-center font-mono text-[.68rem] leading-5 font-black uppercase tracking-[.04em] whitespace-normal text-white sm:w-auto" event="primary_cta_click" href="#diagnostic">Découvrir TR1 sur mon réseau officinal <ArrowRight className="size-4 shrink-0" /></MarketingTrackedLink><a className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-md border border-[#bdb4a6] px-4 text-center font-mono text-xs font-black uppercase tracking-[.06em] sm:w-auto" href="#produit">Voir la preuve produit <ArrowDown className="size-4" /></a></div><p className="mt-3 text-sm text-[#66717d]">Diagnostic et démonstration personnalisée de 30 minutes.</p></div><LeadForm /></div></section>
    <section className="border-b border-[#d8d0c2] px-5 py-16 lg:px-8"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-[#c9562d]">Le constat</p><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.05em]">Votre réseau grandit. Votre organisation doit pouvoir suivre.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-xl border border-[#d8d0c2] bg-[#d8d0c2] md:grid-cols-3">{["Les données commerciales sont dispersées.","Les intervenants utilisent des méthodes différentes.","Le management manque de visibilité sur les comptes à développer."].map((item,index)=><div className="bg-[#fffaf0] p-6" key={item}><span className="font-mono text-xs text-[#c9562d]">0{index+1}</span><p className="mt-4 text-lg font-semibold">{item}</p></div>)}</div><p className="mt-8 text-xl font-semibold">TR1 transforme une organisation dispersée en un système commercial commun.</p></div></section>
    <section className="border-b border-[#d8d0c2] px-5 py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-5 lg:grid-cols-3">{pillars.map(({icon:Icon,...pillar})=><article className="rounded-xl border border-[#d8d0c2] bg-[#fffaf0] p-6" key={pillar.title}><Icon className="size-6 text-[#c9562d]"/><h2 className="mt-6 text-2xl font-black tracking-[-.04em]">{pillar.title}</h2><p className="mt-3 leading-7 text-[#596574]">{pillar.text}</p><ul className="mt-6 grid gap-2 font-mono text-xs uppercase tracking-[.04em]">{pillar.items.map(item=><li className="border-t border-[#e0d8cb] pt-2" key={item}>{item}</li>)}</ul></article>)}</div></div></section>
    <section className="border-b border-[#d8d0c2] px-5 py-16 lg:px-8" id="produit"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-[#c9562d]">Preuve produit</p><h2 className="mt-3 mb-9 text-4xl font-black tracking-[-.05em]">Un même scénario, de la priorité au résultat terrain.</h2><ProductProof /></div></section>
    <section className="border-b border-[#d8d0c2] px-5 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2">{[{title:"Vos ressources existantes",message:"Vous ne changez pas votre organisation. Vous lui donnez un système commun.",items:"Commerciaux salariés · Agents déjà mandatés · Animateurs · Formateurs · Managers"},{title:"Les ressources validées par TR1",message:"Complétez votre dispositif selon les territoires, les besoins et la disponibilité des profils.",items:"Agents commerciaux · Animateurs · Formateurs · Intervenants terrain"}].map((block,index)=><article className="rounded-xl border border-[#d8d0c2] bg-[#fffaf0] p-7" key={block.title}><ShieldCheck className={`size-7 ${index ? "text-[#c9562d]" : "text-[#0f2740]"}`}/><h2 className="mt-5 text-2xl font-black tracking-[-.04em]">{block.title}</h2><p className="mt-4 text-lg leading-8">{block.message}</p><p className="mt-6 border-t border-[#d8d0c2] pt-4 font-mono text-xs uppercase leading-6 tracking-[.04em] text-[#596574]">{block.items}</p></article>)}</div></section>
    <section className="bg-[#0f2740] px-5 py-16 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-[#e9784d]">Votre prochain marché officinal</p><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.05em]">Voyons comment TR1 s’adapte à votre réseau et à vos équipes.</h2></div><MarketingTrackedLink className="inline-flex min-h-12 w-full shrink-0 items-center justify-center rounded-md bg-[#f5efe4] px-4 text-center font-mono text-[.68rem] leading-5 font-black uppercase tracking-[.04em] whitespace-normal text-[#0f2740] sm:w-auto" event="primary_cta_click" href="#diagnostic">Découvrir TR1 sur mon réseau officinal</MarketingTrackedLink></div></section>
  </main>;
}
