create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;

create type public.membership_status as enum ('invited', 'active', 'suspended');
create type public.pharmacy_status as enum (
  'targeted', 'qualified', 'contacted', 'appointment_scheduled', 'offer_sent',
  'pending_order', 'implanted', 'active', 'to_develop', 'dormant', 'lost'
);
create type public.agent_kind as enum ('commercial', 'facilitator', 'trainer');
create type public.interaction_kind as enum ('call', 'email', 'visit', 'meeting', 'note');
create type public.task_status as enum ('todo', 'in_progress', 'done', 'cancelled');
create type public.order_status as enum ('draft', 'submitted', 'confirmed', 'cancelled');
create type public.mission_status as enum ('planned', 'in_progress', 'completed', 'cancelled');

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  is_platform_owner boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index organizations_single_platform_owner
  on public.organizations (is_platform_owner) where is_platform_owner;

create table public.brands (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  managed_by_organization_id uuid not null references public.organizations(id) on delete restrict,
  name text not null,
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_url text,
  onboarding_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.roles (
  id smallint generated by default as identity primary key,
  key text not null unique check (key in ('super_admin', 'tr1_manager', 'brand_admin', 'brand_user', 'agent', 'facilitator')),
  label text not null,
  description text not null,
  rank smallint not null check (rank between 0 and 100),
  permissions jsonb not null default '{}'::jsonb
);

insert into public.roles (key, label, description, rank, permissions) values
  ('super_admin', 'Super administrateur TR1', 'Accès global à toute la plateforme.', 100, '{"platform.manage":true,"users.manage":true,"brand.read":true}'),
  ('tr1_manager', 'Responsable TR1', 'Accès aux marques attribuées.', 80, '{"users.manage":true,"brand.read":true,"operations.manage":true}'),
  ('brand_admin', 'Administrateur de marque', 'Administration complète de sa marque.', 60, '{"users.manage":true,"brand.read":true,"operations.manage":true}'),
  ('brand_user', 'Utilisateur de marque', 'Lecture ou opérations limitées selon permissions.', 40, '{"brand.read":true,"operations.manage":false}'),
  ('agent', 'Agent commercial', 'Accès aux comptes et tâches affectés.', 20, '{"assignments.operate":true}'),
  ('facilitator', 'Animateur / formateur', 'Accès aux missions et comptes rendus affectés.', 20, '{"missions.operate":true}');

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  brand_id uuid references public.brands(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete restrict,
  permissions jsonb not null default '{}'::jsonb,
  status public.membership_status not null default 'invited',
  invited_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, organization_id, brand_id, role_id)
);

create index memberships_user_brand_idx on public.memberships(user_id, brand_id) where status = 'active';
create index memberships_brand_idx on public.memberships(brand_id);

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  name text not null,
  external_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, name)
);

create table public.territories (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  name text not null,
  code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, name)
);

create table public.pharmacies (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  group_id uuid references public.groups(id) on delete set null,
  territory_id uuid references public.territories(id) on delete set null,
  name text not null,
  status public.pharmacy_status not null default 'targeted',
  address_line1 text,
  postal_code text,
  city text,
  country_code char(2) not null default 'FR',
  external_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, external_code)
);

create index pharmacies_brand_status_idx on public.pharmacies(brand_id, status);
create index pharmacies_territory_idx on public.pharmacies(territory_id);

create table public.pharmacy_contacts (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  full_name text not null,
  job_title text,
  email text,
  phone text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, name)
);

create table public.product_references (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  sku text not null,
  ean text,
  label text not null,
  unit_price numeric(12,2) check (unit_price is null or unit_price >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, sku)
);

create table public.agents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  kind public.agent_kind not null,
  external_code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, kind)
);

create table public.agent_brand_assignments (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  agent_id uuid not null references public.agents(id) on delete cascade,
  starts_at date not null default current_date,
  ends_at date,
  created_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at),
  unique (brand_id, agent_id, starts_at)
);

create table public.pharmacy_assignments (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  agent_id uuid not null references public.agents(id) on delete cascade,
  assigned_by uuid references public.users(id) on delete set null,
  starts_at date not null default current_date,
  ends_at date,
  created_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at),
  unique (pharmacy_id, agent_id, starts_at)
);

create index pharmacy_assignments_agent_idx on public.pharmacy_assignments(agent_id, brand_id);

create table public.interactions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid not null references public.brands(id) on delete cascade,
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete restrict,
  kind public.interaction_kind not null,
  occurred_at timestamptz not null default now(),
  summary text not null,
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid not null references public.brands(id) on delete cascade,
  pharmacy_id uuid references public.pharmacies(id) on delete cascade,
  assigned_to_user_id uuid not null references public.users(id) on delete cascade,
  created_by_user_id uuid not null references public.users(id) on delete restrict,
  title text not null,
  description text,
  due_at timestamptz,
  status public.task_status not null default 'todo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid not null references public.brands(id) on delete cascade,
  pharmacy_id uuid not null references public.pharmacies(id) on delete restrict,
  created_by_user_id uuid not null references public.users(id) on delete restrict,
  status public.order_status not null default 'draft',
  ordered_at timestamptz,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid not null references public.brands(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_reference_id uuid not null references public.product_references(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create table public.missions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid not null references public.brands(id) on delete cascade,
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  intervenor_user_id uuid not null references public.users(id) on delete restrict,
  title text not null,
  briefing text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status public.mission_status not null default 'planned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);

create table public.mission_reports (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid not null references public.brands(id) on delete cascade,
  mission_id uuid not null references public.missions(id) on delete cascade,
  author_user_id uuid not null references public.users(id) on delete restrict,
  content jsonb not null default '{}'::jsonb,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (mission_id, author_user_id)
);

create table public.activity_logs (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  brand_id uuid references public.brands(id) on delete cascade,
  actor_user_id uuid references public.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index activity_logs_brand_created_idx on public.activity_logs(brand_id, created_at desc);

alter table public.brands add constraint brands_id_organization_unique unique (id, organization_id);
alter table public.memberships add constraint memberships_brand_organization_fk
  foreign key (brand_id, organization_id) references public.brands(id, organization_id) on delete cascade;
alter table public.groups add constraint groups_id_brand_unique unique (id, brand_id);
alter table public.territories add constraint territories_id_brand_unique unique (id, brand_id);
alter table public.pharmacies add constraint pharmacies_id_brand_unique unique (id, brand_id);
alter table public.pharmacies add constraint pharmacies_group_brand_fk
  foreign key (group_id, brand_id) references public.groups(id, brand_id);
alter table public.pharmacies add constraint pharmacies_territory_brand_fk
  foreign key (territory_id, brand_id) references public.territories(id, brand_id);
alter table public.pharmacy_contacts add constraint pharmacy_contacts_pharmacy_brand_fk
  foreign key (pharmacy_id, brand_id) references public.pharmacies(id, brand_id) on delete cascade;
alter table public.products add constraint products_id_brand_unique unique (id, brand_id);
alter table public.product_references add constraint product_references_id_brand_unique unique (id, brand_id);
alter table public.product_references add constraint product_references_product_brand_fk
  foreign key (product_id, brand_id) references public.products(id, brand_id) on delete cascade;
alter table public.agent_brand_assignments add constraint agent_brand_id_brand_unique unique (id, brand_id);
alter table public.pharmacy_assignments add constraint pharmacy_assignments_pharmacy_brand_fk
  foreign key (pharmacy_id, brand_id) references public.pharmacies(id, brand_id) on delete cascade;
alter table public.interactions add constraint interactions_brand_organization_fk
  foreign key (brand_id, organization_id) references public.brands(id, organization_id);
alter table public.interactions add constraint interactions_pharmacy_brand_fk
  foreign key (pharmacy_id, brand_id) references public.pharmacies(id, brand_id) on delete cascade;
alter table public.tasks add constraint tasks_brand_organization_fk
  foreign key (brand_id, organization_id) references public.brands(id, organization_id);
alter table public.tasks add constraint tasks_pharmacy_brand_fk
  foreign key (pharmacy_id, brand_id) references public.pharmacies(id, brand_id) on delete cascade;
alter table public.orders add constraint orders_id_brand_organization_unique unique (id, brand_id, organization_id);
alter table public.orders add constraint orders_brand_organization_fk
  foreign key (brand_id, organization_id) references public.brands(id, organization_id);
alter table public.orders add constraint orders_pharmacy_brand_fk
  foreign key (pharmacy_id, brand_id) references public.pharmacies(id, brand_id);
alter table public.order_items add constraint order_items_order_tenant_fk
  foreign key (order_id, brand_id, organization_id) references public.orders(id, brand_id, organization_id) on delete cascade;
alter table public.order_items add constraint order_items_product_reference_brand_fk
  foreign key (product_reference_id, brand_id) references public.product_references(id, brand_id);
alter table public.missions add constraint missions_id_brand_organization_unique unique (id, brand_id, organization_id);
alter table public.missions add constraint missions_brand_organization_fk
  foreign key (brand_id, organization_id) references public.brands(id, organization_id);
alter table public.missions add constraint missions_pharmacy_brand_fk
  foreign key (pharmacy_id, brand_id) references public.pharmacies(id, brand_id) on delete cascade;
alter table public.mission_reports add constraint mission_reports_mission_tenant_fk
  foreign key (mission_id, brand_id, organization_id) references public.missions(id, brand_id, organization_id) on delete cascade;
alter table public.activity_logs add constraint activity_logs_brand_organization_fk
  foreign key (brand_id, organization_id) references public.brands(id, organization_id) on delete cascade;

create or replace function private.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'organizations','brands','users','user_profiles','memberships','groups','territories',
    'pharmacies','pharmacy_contacts','products','product_references','agents','interactions',
    'tasks','orders','missions','mission_reports'
  ] loop
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function private.set_updated_at()', table_name, table_name);
  end loop;
end $$;

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.users (id, email) values (new.id, coalesce(new.email, ''));
  insert into public.user_profiles (user_id, full_name)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

revoke all on function private.handle_new_auth_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users
for each row execute function private.handle_new_auth_user();

create or replace function private.activate_invited_memberships()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.onboarding_completed_at is null and new.onboarding_completed_at is not null then
    update public.memberships set status = 'active' where user_id = new.user_id and status = 'invited';
  end if;
  return new;
end;
$$;

revoke all on function private.activate_invited_memberships() from public, anon, authenticated;
create trigger activate_memberships_after_onboarding after update on public.user_profiles
for each row execute function private.activate_invited_memberships();

create or replace function private.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_data jsonb;
  target_brand_id uuid;
  target_organization_id uuid;
  target_entity_id uuid;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  target_brand_id := nullif(row_data ->> 'brand_id', '')::uuid;
  target_organization_id := nullif(row_data ->> 'organization_id', '')::uuid;
  target_entity_id := nullif(row_data ->> 'id', '')::uuid;

  if tg_table_name = 'brands' then
    target_brand_id := target_entity_id;
  end if;

  if target_organization_id is null and target_brand_id is not null then
    select b.organization_id into target_organization_id from public.brands b where b.id = target_brand_id;
  end if;

  if target_organization_id is not null then
    insert into public.activity_logs (
      organization_id, brand_id, actor_user_id, action, entity_type, entity_id, old_data, new_data
    ) values (
      target_organization_id,
      target_brand_id,
      (select auth.uid()),
      lower(tg_table_name || '.' || tg_op),
      tg_table_name,
      target_entity_id,
      case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end,
      case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end
    );
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function private.audit_row_change() from public, anon, authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'brands','memberships','pharmacies','products','product_references','agent_brand_assignments',
    'pharmacy_assignments','orders','missions','mission_reports'
  ] loop
    execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function private.audit_row_change()', table_name, table_name);
  end loop;
end $$;

create or replace function private.has_global_role(role_keys text[])
returns boolean
language sql stable security definer set search_path = ''
as $$
  select (select auth.uid()) is not null and exists (
    select 1 from public.memberships m
    join public.roles r on r.id = m.role_id
    where m.user_id = (select auth.uid()) and m.status = 'active'
      and m.brand_id is null and r.key = any(role_keys)
  );
$$;

create or replace function private.has_brand_role(target_brand_id uuid, role_keys text[])
returns boolean
language sql stable security definer set search_path = ''
as $$
  select (select auth.uid()) is not null and (
    private.has_global_role(array['super_admin']) or exists (
      select 1 from public.memberships m
      join public.roles r on r.id = m.role_id
      where m.user_id = (select auth.uid()) and m.status = 'active'
        and m.brand_id = target_brand_id and r.key = any(role_keys)
    )
  );
$$;

create or replace function private.has_brand_permission(target_brand_id uuid, permission_key text)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select private.has_global_role(array['super_admin']) or coalesce((
    select bool_or(coalesce(m.permissions ->> permission_key, r.permissions ->> permission_key)::boolean)
    from public.memberships m
    join public.roles r on r.id = m.role_id
    where m.user_id = (select auth.uid()) and m.status = 'active' and m.brand_id = target_brand_id
  ), false);
$$;

create or replace function private.can_assign_role(target_brand_id uuid, target_role_id smallint)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select private.has_global_role(array['super_admin']) or exists (
    select 1
    from public.roles target_role
    where target_role.id = target_role_id
      and target_role.key not in ('super_admin', 'tr1_manager')
      and target_role.rank <= coalesce((
        select max(author_role.rank)
        from public.memberships author_membership
        join public.roles author_role on author_role.id = author_membership.role_id
        where author_membership.user_id = (select auth.uid())
          and author_membership.brand_id = target_brand_id
          and author_membership.status = 'active'
      ), 0)
  );
$$;

create or replace function private.can_access_brand(target_brand_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_global_role(array['super_admin']) or exists (
    select 1 from public.memberships m
    where m.user_id = (select auth.uid()) and m.status = 'active' and m.brand_id = target_brand_id
  );
$$;

create or replace function private.has_elevated_brand_access(target_brand_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_brand_role(target_brand_id, array['tr1_manager','brand_admin','brand_user']);
$$;

create or replace function public.can_manage_brand_users(target_brand_id uuid)
returns boolean language sql stable security invoker set search_path = '' as $$
  select private.has_brand_permission(target_brand_id, 'users.manage');
$$;

create or replace function public.get_my_brand_contexts()
returns table (brand_id uuid, brand_name text, brand_slug text, role_key text)
language sql stable security invoker set search_path = '' as $$
  select b.id, b.name, b.slug,
    case
      when private.has_global_role(array['super_admin']) then 'super_admin'
      else (
        select r.key from public.memberships m
        join public.roles r on r.id = m.role_id
        where m.user_id = (select auth.uid()) and m.brand_id = b.id and m.status = 'active'
        order by r.id limit 1
      )
    end
  from public.brands b
  where b.is_active and private.can_access_brand(b.id)
  order by b.name;
$$;

create or replace function private.can_manage_user(target_user_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_global_role(array['super_admin']) or exists (
    select 1 from public.memberships target
    where target.user_id = target_user_id and target.brand_id is not null
      and private.has_brand_role(target.brand_id, array['tr1_manager','brand_admin'])
  );
$$;

create or replace function private.can_access_pharmacy(target_pharmacy_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.pharmacies p where p.id = target_pharmacy_id and (
      private.has_elevated_brand_access(p.brand_id) or exists (
        select 1 from public.pharmacy_assignments pa
        join public.agents a on a.id = pa.agent_id
        where pa.pharmacy_id = p.id and a.user_id = (select auth.uid())
          and pa.starts_at <= current_date and (pa.ends_at is null or pa.ends_at >= current_date)
      )
    )
  );
$$;

create or replace function private.can_access_mission(target_mission_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.missions m where m.id = target_mission_id and (
      private.has_elevated_brand_access(m.brand_id) or m.intervenor_user_id = (select auth.uid())
    )
  );
$$;

revoke all on all functions in schema private from public, anon;
grant execute on function private.has_global_role(text[]) to authenticated;
grant execute on function private.has_brand_role(uuid,text[]) to authenticated;
grant execute on function private.has_brand_permission(uuid,text) to authenticated;
grant execute on function private.can_assign_role(uuid,smallint) to authenticated;
grant execute on function private.can_access_brand(uuid) to authenticated;
grant execute on function private.has_elevated_brand_access(uuid) to authenticated;
grant execute on function private.can_manage_user(uuid) to authenticated;
grant execute on function private.can_access_pharmacy(uuid) to authenticated;
grant execute on function private.can_access_mission(uuid) to authenticated;
revoke all on function public.can_manage_brand_users(uuid) from public, anon;
grant execute on function public.can_manage_brand_users(uuid) to authenticated, service_role;
revoke all on function public.get_my_brand_contexts() from public, anon;
grant execute on function public.get_my_brand_contexts() to authenticated, service_role;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'organizations','brands','users','user_profiles','roles','memberships','groups','territories',
    'pharmacies','pharmacy_contacts','products','product_references','agents','agent_brand_assignments',
    'pharmacy_assignments','interactions','tasks','orders','order_items','missions','mission_reports','activity_logs'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on public.%I from anon', table_name);
  end loop;
end $$;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

create policy organizations_select on public.organizations for select to authenticated
using (private.has_global_role(array['super_admin']) or exists (
  select 1 from public.memberships m where m.organization_id = id and m.user_id = (select auth.uid()) and m.status = 'active'
));
create policy organizations_manage on public.organizations for all to authenticated
using (private.has_global_role(array['super_admin'])) with check (private.has_global_role(array['super_admin']));

create policy brands_select on public.brands for select to authenticated using (private.can_access_brand(id));
create policy brands_manage on public.brands for all to authenticated
using (private.has_global_role(array['super_admin'])) with check (private.has_global_role(array['super_admin']));

create policy users_select on public.users for select to authenticated
using (id = (select auth.uid()) or private.can_manage_user(id));
create policy profiles_select on public.user_profiles for select to authenticated
using (user_id = (select auth.uid()) or private.can_manage_user(user_id));
create policy profiles_update_self on public.user_profiles for update to authenticated
using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

create policy roles_select on public.roles for select to authenticated using (true);

create policy memberships_select on public.memberships for select to authenticated
using (user_id = (select auth.uid()) or (brand_id is not null and public.can_manage_brand_users(brand_id)) or private.has_global_role(array['super_admin']));
create policy memberships_insert on public.memberships for insert to authenticated
with check (
  brand_id is not null
  and public.can_manage_brand_users(brand_id)
  and private.can_assign_role(brand_id, role_id)
);
create policy memberships_update on public.memberships for update to authenticated
using (brand_id is not null and public.can_manage_brand_users(brand_id))
with check (
  brand_id is not null
  and public.can_manage_brand_users(brand_id)
  and private.can_assign_role(brand_id, role_id)
);
create policy memberships_delete on public.memberships for delete to authenticated
using (brand_id is not null and public.can_manage_brand_users(brand_id));

create policy groups_select on public.groups for select to authenticated using (private.can_access_brand(brand_id));
create policy groups_manage on public.groups for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));
create policy territories_select on public.territories for select to authenticated using (private.can_access_brand(brand_id));
create policy territories_manage on public.territories for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));

create policy pharmacies_select on public.pharmacies for select to authenticated using (private.can_access_pharmacy(id));
create policy pharmacies_manage on public.pharmacies for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));

create policy pharmacy_contacts_select on public.pharmacy_contacts for select to authenticated using (private.can_access_pharmacy(pharmacy_id));
create policy pharmacy_contacts_operate on public.pharmacy_contacts for all to authenticated
using (private.can_access_pharmacy(pharmacy_id))
with check (private.can_access_pharmacy(pharmacy_id) and private.can_access_brand(brand_id));

create policy products_select on public.products for select to authenticated using (private.can_access_brand(brand_id));
create policy products_manage on public.products for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));
create policy product_references_select on public.product_references for select to authenticated using (private.can_access_brand(brand_id));
create policy product_references_manage on public.product_references for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));

create policy agents_select on public.agents for select to authenticated
using (user_id = (select auth.uid()) or private.can_manage_user(user_id));
create policy agents_manage on public.agents for all to authenticated
using (private.can_manage_user(user_id)) with check (private.can_manage_user(user_id));
create policy agent_brands_select on public.agent_brand_assignments for select to authenticated
using (private.can_access_brand(brand_id) and (private.has_elevated_brand_access(brand_id) or exists (
  select 1 from public.agents a where a.id = agent_id and a.user_id = (select auth.uid())
)));
create policy agent_brands_manage on public.agent_brand_assignments for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));

create policy pharmacy_assignments_select on public.pharmacy_assignments for select to authenticated
using (private.has_elevated_brand_access(brand_id) or exists (
  select 1 from public.agents a where a.id = agent_id and a.user_id = (select auth.uid())
));
create policy pharmacy_assignments_manage on public.pharmacy_assignments for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));

create policy interactions_select on public.interactions for select to authenticated using (private.can_access_pharmacy(pharmacy_id));
create policy interactions_insert on public.interactions for insert to authenticated
with check (user_id = (select auth.uid()) and private.can_access_pharmacy(pharmacy_id) and private.can_access_brand(brand_id));
create policy interactions_update on public.interactions for update to authenticated
using (user_id = (select auth.uid()) or private.has_elevated_brand_access(brand_id))
with check (private.can_access_pharmacy(pharmacy_id) and private.can_access_brand(brand_id));

create policy tasks_select on public.tasks for select to authenticated
using (private.has_elevated_brand_access(brand_id) or assigned_to_user_id = (select auth.uid()));
create policy tasks_insert on public.tasks for insert to authenticated
with check (created_by_user_id = (select auth.uid()) and private.can_access_brand(brand_id));
create policy tasks_update on public.tasks for update to authenticated
using (private.has_elevated_brand_access(brand_id) or assigned_to_user_id = (select auth.uid()))
with check (private.can_access_brand(brand_id));

create policy orders_select on public.orders for select to authenticated using (private.can_access_pharmacy(pharmacy_id));
create policy orders_insert on public.orders for insert to authenticated
with check (created_by_user_id = (select auth.uid()) and private.can_access_pharmacy(pharmacy_id) and private.can_access_brand(brand_id));
create policy orders_update on public.orders for update to authenticated
using (created_by_user_id = (select auth.uid()) or private.has_elevated_brand_access(brand_id))
with check (private.can_access_pharmacy(pharmacy_id) and private.can_access_brand(brand_id));
create policy order_items_select on public.order_items for select to authenticated
using (exists (select 1 from public.orders o where o.id = order_id and private.can_access_pharmacy(o.pharmacy_id)));
create policy order_items_operate on public.order_items for all to authenticated
using (exists (select 1 from public.orders o where o.id = order_id and (o.created_by_user_id = (select auth.uid()) or private.has_elevated_brand_access(o.brand_id))))
with check (private.can_access_brand(brand_id));

create policy missions_select on public.missions for select to authenticated using (private.can_access_mission(id));
create policy missions_manage on public.missions for all to authenticated
using (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']))
with check (private.has_brand_role(brand_id, array['tr1_manager','brand_admin']));
create policy mission_reports_select on public.mission_reports for select to authenticated using (private.can_access_mission(mission_id));
create policy mission_reports_insert on public.mission_reports for insert to authenticated
with check (author_user_id = (select auth.uid()) and private.can_access_mission(mission_id) and private.can_access_brand(brand_id));
create policy mission_reports_update on public.mission_reports for update to authenticated
using (author_user_id = (select auth.uid()) or private.has_elevated_brand_access(brand_id))
with check (private.can_access_mission(mission_id) and private.can_access_brand(brand_id));

create policy activity_logs_select on public.activity_logs for select to authenticated
using ((brand_id is not null and private.has_elevated_brand_access(brand_id)) or private.has_global_role(array['super_admin']));
create policy activity_logs_insert on public.activity_logs for insert to authenticated
with check (actor_user_id = (select auth.uid()) and (brand_id is null or private.can_access_brand(brand_id)));

comment on schema private is 'Fonctions internes d’autorisation. Non exposé par la Data API.';
comment on function public.can_manage_brand_users(uuid) is 'Autorité centrale utilisée par l’UI serveur et les politiques RLS pour administrer une équipe de marque.';
