import Link from "next/link";
import { notFound } from "next/navigation";
import { approvePilotAction, preparePilotAction, updateLeadAction } from "@/app/(protected)/dashboard/admin/leads/actions";
import { requirePlatformAdmin } from "@/lib/auth";
import { leadStatuses } from "@/lib/marketing/leads";

export default async function LeadDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const { id } = await params; const notices = await searchParams; const { supabase } = await requirePlatformAdmin();
  const [{ data: lead }, { data: pilots }, { data: events }, { data: memberships }] = await Promise.all([
    supabase.from("commercial_leads").select("*").eq("id", id).single(),
    supabase.from("pilot_projects").select("*").eq("lead_id", id).order("created_at",{ascending:false}),
    supabase.from("commercial_lead_events").select("id,event_name,metadata,created_at").eq("lead_id", id).order("created_at",{ascending:false}),
    supabase.from("memberships").select("user_id,users!memberships_user_id_fkey(user_profiles(full_name))").is("brand_id",null).eq("status","active"),
  ]);
  if (!lead) notFound();
  const assignees = (memberships ?? []).map((membership) => { const user=Array.isArray(membership.users)?membership.users[0]:membership.users; const profile=Array.isArray(user?.user_profiles)?user.user_profiles[0]:user?.user_profiles; return {id:membership.user_id,name:profile?.full_name??"Responsable TR1"}; });
  const pilot = pilots?.[0];
  return <div className="space-y-6"><Link className="text-sm underline" href="/dashboard/admin/leads">← Tous les leads</Link><div><p className="tr1-da-eyebrow">{lead.status}</p><h1 className="tr1-da-title">{lead.company_name}</h1><p className="mt-2 text-muted-foreground">{lead.full_name} · {lead.professional_email}</p></div>{notices.onboarding?<p className="rounded-lg border border-green-200 bg-green-50 p-4 text-green-900">Organisation et marque brouillon créées via l’onboarding Sprint 11.</p>:null}
    <div className="grid gap-6 xl:grid-cols-2"><form action={updateLeadAction} className="space-y-4 rounded-lg border bg-card p-5"><h2 className="font-mono text-lg font-black uppercase">Qualification</h2><input name="leadId" type="hidden" value={lead.id}/><label className="grid gap-2 text-sm">Statut<select className="h-10 rounded-md border bg-background px-3" defaultValue={lead.status} name="status">{leadStatuses.map(status=><option key={status}>{status}</option>)}</select></label><label className="grid gap-2 text-sm">Responsable<select className="h-10 rounded-md border bg-background px-3" defaultValue={lead.assigned_to??""} name="assignedTo"><option value="">Non attribué</option>{assignees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-2 text-sm">Prochaine action<input className="h-10 rounded-md border bg-background px-3" defaultValue={lead.next_action_at?.slice(0,16)} name="nextActionAt" type="datetime-local"/></label><label className="grid gap-2 text-sm">Notes internes<textarea className="min-h-32 rounded-md border bg-background p-3" defaultValue={lead.internal_notes??""} maxLength={4000} name="internalNotes"/></label><button className="rounded-md bg-primary px-4 py-2 font-mono text-xs font-bold uppercase text-primary-foreground">Enregistrer</button></form>
      {!pilot?<form action={preparePilotAction} className="space-y-4 rounded-lg border bg-card p-5"><h2 className="font-mono text-lg font-black uppercase">Préparer un pilote</h2><p className="text-sm text-muted-foreground">Disponible uniquement après qualification. Cette action crée un brouillon, jamais une marque active.</p><input name="leadId" type="hidden" value={lead.id}/><label className="grid gap-2 text-sm">Organisation proposée<input className="h-10 rounded-md border bg-background px-3" defaultValue={lead.company_name} name="proposedOrganizationName" required/></label><label className="grid gap-2 text-sm">Marque proposée<input className="h-10 rounded-md border bg-background px-3" defaultValue={lead.company_name} name="proposedBrandName" required/></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-sm">Pays<input className="h-10 rounded-md border bg-background px-3" defaultValue="FR" maxLength={2} name="countryOrScope"/></label><label className="grid gap-2 text-sm">Utilisateurs<input className="h-10 rounded-md border bg-background px-3" min={1} name="estimatedUsers" type="number"/></label></div><label className="grid gap-2 text-sm">Démarrage proposé<input className="h-10 rounded-md border bg-background px-3" name="proposedStartDate" type="date"/></label><label className="flex gap-2 text-sm"><input name="confirmation" required type="checkbox" value="true"/>Je confirme la préparation explicite de ce brouillon.</label><button className="rounded-md bg-primary px-4 py-2 font-mono text-xs font-bold uppercase text-primary-foreground" disabled={lead.status!=="qualified"}>Préparer le pilote</button></form>:<div className="space-y-4 rounded-lg border bg-card p-5"><p className="tr1-da-eyebrow">Projet pilote</p><h2 className="font-mono text-xl font-black uppercase">{pilot.proposed_brand_name}</h2><p className="text-sm">Statut : <strong>{pilot.status}</strong></p><p className="text-sm text-muted-foreground">L’environnement reste inactif jusqu’à la fin de la checklist d’onboarding.</p>{pilot.status==="draft"?<form action={approvePilotAction} className="space-y-3"><input name="pilotId" type="hidden" value={pilot.id}/><input name="leadId" type="hidden" value={lead.id}/><label className="flex gap-2 text-sm"><input name="confirmation" required type="checkbox" value="true"/>J’approuve la création de l’organisation et de la marque brouillon.</label><button className="rounded-md bg-[#c9562d] px-4 py-2 font-mono text-xs font-bold uppercase text-white">Approuver et ouvrir l’onboarding</button></form>:null}{pilot.brand_id?<Link className="inline-block text-sm underline" href="/dashboard/admin/onboarding">Continuer l’onboarding</Link>:null}</div>}
    </div><section className="rounded-lg border bg-card p-5"><h2 className="font-mono text-lg font-black uppercase">Historique append-only</h2><div className="mt-4 space-y-3">{(events??[]).map(event=><div className="flex justify-between gap-4 border-t pt-3 text-sm" key={event.id}><span className="font-mono uppercase">{event.event_name.replaceAll("_"," ")}</span><time className="text-muted-foreground">{new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.created_at))}</time></div>)}</div></section>
  </div>;
}
